### ISSUE TITLE
Basic/Page styling

### ISSUE THREAD

**Issue by Noles** [SolderIO/solder#102]
In this Issue I like to discuss a little bit about the basic styling of pages and so on.

My ideas:

- Smaller Font-size: around 14px (the bulma defaults are to big in my opinion)
Example:
+$size-1: 2.5rem;
+$size-2: 2rem;
+$size-3: 1.5rem;
+$size-4: 1.25rem;
+$size-5: 1rem;
+$size-6: 0.75rem;
+$size-7: 0.65rem;

- Reduce section padding top/bottom to 1.5rem (we have so many white space on the pages)

- Bulma Tabs on the Builds and Modpacks pages
![bildschirmfoto vom 2018-03-14 18-20-22](https://user-images.githubusercontent.com/3484086/37419372-9ba4f37e-27b4-11e8-845c-c148aee9508f.png)

**Comment by Indemnity83** [comment]
Yeah, I'm not happy with the way the site looks. I've been toying with alternate layouts including a very basic bootstrap 4 layout:

![screen shot 2018-03-14 at 10 26 15 am](https://user-images.githubusercontent.com/35218/37419683-3c69f05e-2772-11e8-98ce-3b2e285ec0f1.png)

and even played around with a very different layout (ignore the boilerplate elements and colors). This is a bit more like the current version of solder.

![screen shot 2018-03-14 at 10 28 37 am](https://user-images.githubusercontent.com/35218/37419831-914b8eac-2772-11e8-853f-7841550eb2f0.png)

**Comment by Noles** [comment]
Looks promising.

The current pages are in my opinion not well structured. I permanently search for the content I am looking for on every page.  :-)

So Bulma is not the only framework option for you? Thats good to know... I mean it's not bad but I personally have more experience with bootstrap.

**Comment by Indemnity83** [comment]
I'm open to Bulma, Bootstrap or Tailwind.

**Comment by Noles** [comment]
Hmm Tailwind looks a little bit more complicated as there are no built-in components. So why reinvent the wheel when we can get it out of box with bulma or bootstrap!?

How do you like to proceed? And how can I help?

**Comment by Indemnity83** [comment]
My preference would be Bootstrap 4; its likely the most universal which is good for an open source project. 

If you want to mock up a Bootstrap 4 layout I'm very willing to consider it. I may though just start by doing a generic bootstrap layout like my first screenshot to get things into consistent territory.

**Comment by Indemnity83** [comment]
The project will be Bootstrap 4; primarily because I believe it provides us the widest support from the community. The feature/extract-framework implements this already and will be merged into developing when it reaches functional parity. At that point, this issue will be formally closed.

**Comment by Pyker** [comment]
This repository is being archived (see <https://www.technicpack.net/article/solderio-is-shutting-down.199> for extra information), so we're closing this issue.
