### ISSUE TITLE
Can't open the login page

### ISSUE THREAD

**Issue by XeroxDev** [SolderIO/solder#104]
Hey there!

I setted all up, like you posted it in the readme.md, then I setted up apache2 with follow config:
```
Alias /solder "/home/solderio/solder/public/"
        <Directory "/home/solderio/solder/public/">
                Order allow,deny
                Allow from all
                Require all granted
        </Directory>
```
then, if I go the *mydomain*.*mytld*/solder/ it will redirect me to /solder/login

every fine and okay, but then I got the nice 404 error: The requested URL /home/solderio/solder/public/index.php was not found on this server.

Did you know, why this is so?

Kind regards
XeroxDev

and yes, the index.php file is still available.

*edit* And yes², I've activated the htaccess rewrite rule

**Comment by Indemnity83** [comment]
It looks like you're trying to run it in a subfolder?

```
Alias /solder "/home/solderio/solder/public/"
```

This isn't a supported configuration.

**Comment by Noles** [comment]
@Indemnity83 I think we could record this for the planned ui rework. In my opinion we only need to update the current routes in the templates with `{{ route(xxx) }}` function to accomplish this.

**Comment by XeroxDev** [comment]
@Indemnity83 

Okay, and how must I configure it? If I try it in the /solder/ folder, it can't find anything, because there is no index.php file

**Comment by XeroxDev** [comment]
Ok, found it out, currently only subdomains supported. It works now :D
