### ISSUE TITLE
manage teams gives 422 when editing

### ISSUE THREAD

**Issue by Lord-Ptolemy** [SolderIO/solder#119]
When editing a team's name. If you click update without changing anything. It sends a payload of:
```
{"name":""}
```

When editing a team's name, but just clicking outside of the box without clicking Update. It sends a payload of:
```
{"name": null}
```

Both result in a 422 status code being sent back and this popup:
![image](https://user-images.githubusercontent.com/8279453/38471936-20698a8a-3b46-11e8-8bc1-1e1860fe3c37.png)

If I click out of the box or hit update without changing anything. No requests should be sent or at the very least they should send the same name.

**Comment by Indemnity83** [comment]
This is an annoyance of Sweetalert. I want to just replace this with a modal. Going to defer this one for the UI refresh that’s looming shortly.

**Comment by Pyker** [comment]
This repository is being archived (see <https://www.technicpack.net/article/solderio-is-shutting-down.199> for extra information), so we're closing this issue.
