### ISSUE TITLE
Cant Publish Modpack

### ISSUE THREAD

**Issue by CityMC** [SolderIO/solder#121]
After a Clean install and linked back to Technic Platform i want to download the pack over the Technic Launcher and i become this Error 

>"The modpack does not appear to be installed or is corrupt, and is not available for Offline Play."

and when i looked on the Solder Api provided by my installation i see there is no valid recommed or latest version!

`{"name":"citymc-beta","display_name":"CityMC","recommended":null,"latest":null,"builds":["5.2.1","5.3.0","5.4.0"]}`

But i have Marked the latest version 5.4.0 at this moment as Recommed and Latst in the UI. (both slot marked as green)

any Idea how this happend?

**Comment by CityMC** [comment]
After a littlebit of testing all the other Settings like name and new builds will be updated instantly but i can change the Latest and Recommend buttons frequently with no update in the API...

Same at a new Modpack
`{"name":"example","display_name":"Example","recommended":null,"latest":null,"builds":["1.0.0"]}`

**Comment by Indemnity83** [comment]
Looks like I forgot to fix the launcher-api.php config when I extracted the api to its own package.

**Comment by Indemnity83** [comment]
Thanks, 

give it an update, should be working now.
