### ISSUE TITLE
Build settings in api coming up as null.

### ISSUE THREAD

**Issue by gartia** [SolderIO/solder#123]
So all the settings here https://i.imgur.com/pn9fqIY.png come up as null in the api when trying to download a pack. https://i.imgur.com/dwWSCl9.png The pack wont download because of the missing information i believe. Is this a known thing that has happened?
I'm running this on debian 9 stretch and using nginx everything else seems to work fine downloading mods and stuff. 

Text version of the missing info if needed
`{"minecraft":null,"java":null,"memory":0,"forge":null,"mods":[-snipped the mods list-]}`

**Comment by Indemnity83** [comment]
Thanks for posting the issue, I had another config error after extracting the API to its own package. If you [upgrade](https://github.com/TechnicPack/solder#upgrading) you should be back in working order.
