### ISSUE TITLE
[Feature] Docker support

### ISSUE THREAD

**Issue by zlepper** [SolderIO/solder#124]
It would be lovely with an officially supported docker image, which would make it a whole lot easier to get solder up and running. 

Currently looking in to getting it working, so will see if I can get a PR open soon-ish.

**Comment by Indemnity83** [comment]
That would be great. Feel free to use https://github.com/Indemnity83/solder-docker as a base, or cherry pick the parts you find useful.

**Comment by zlepper** [comment]
What database engine should be used in the compose? I'm partial to Postgres, but I see you went with mysql?

**Comment by Indemnity83** [comment]
Either should work, but I've not confirmed it with postgres. SQLite would work  too and be less resource intensive.

**Comment by Pyker** [comment]
This repository is being archived (see <https://www.technicpack.net/article/solderio-is-shutting-down.199> for extra information), so we're closing this issue.
