### ISSUE TITLE
Version in /api is 0.7.3.1 instead of 0.8.x

### ISSUE THREAD

**Issue by bochen415** [SolderIO/solder#129]
As tiltle
`{"api":"Solder","version":"0.7.3.1","stream":null}`

**Comment by Indemnity83** [comment]
Note it should actually by 1.0.0-alpha technically

**Comment by Pyker** [comment]
This repository is being archived (see <https://www.technicpack.net/article/solderio-is-shutting-down.199> for extra information), so we're closing this issue.
