### ISSUE TITLE
Mods are downloaded in the launcher with Pretty Name instead of mod slug

### ISSUE THREAD

**Issue by bochen415** [SolderIO/solder#130]
The launcher when downloading the files to modpacks/modpack_name/cache is using the Pretty Name so any mod (package) that has invalid filename characters (like`:` on windows) in the name is not downloaded properly giving you a 0 byte file.
example:
![](https://i.imgur.com/7beWX78.png)

**Comment by Pyker** [comment]
This repository is being archived (see <https://www.technicpack.net/article/solderio-is-shutting-down.199> for extra information), so we're closing this issue.
