### ISSUE TITLE
Problems with accessing the top gui bar on mobile devices

### ISSUE THREAD

**Issue by bochen415** [SolderIO/solder#131]
The top bar with Library, Settings and the profile menu is not visible on mobile devices.
Tried 3 devices with 2 different browsers, the only one which showed me this specific part of the gui was a tablet in horizontal mode (not visible in vertical mode).

**Comment by Indemnity83** [comment]
Thanks, I've got a rebuild of the styling coming down the pipeline which should fix this.

**Comment by Pyker** [comment]
This repository is being archived (see <https://www.technicpack.net/article/solderio-is-shutting-down.199> for extra information), so we're closing this issue.
