### ISSUE TITLE
[Feature] Allow package/modpack/release filtering like it was with 0.7

### ISSUE THREAD

**Issue by bochen415** [SolderIO/solder#132]
![](https://i.imgur.com/pxQReJo.png)

**Comment by Indemnity83** [comment]
Implemented in https://github.com/TechnicPack/solder-framework/commit/12ac9a2a8de7395920b1baa9b1db027b6f5c03ae

**Comment by Indemnity83** [comment]
To be clear this is currently part of the `feature/extract-framework` branch and will get rolled into develop when that branch reaches functional parity.

**Comment by Indemnity83** [comment]
Leaving open until the feature branch is merged

**Comment by Indemnity83** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/35218/48649606-fc822d00-e9a7-11e8-8339-180781e58abb.gif)

**Comment by Pyker** [comment]
This repository is being archived (see <https://www.technicpack.net/article/solderio-is-shutting-down.199> for extra information), so we're closing this issue.
