### ISSUE TITLE
[Feature] make Bundled Releases clickable 

### ISSUE THREAD

**Issue by bochen415** [SolderIO/solder#133]
When editing a modpack build the names of Bundled Releases could be clickable and take you to the Release clicked.
![](https://i.imgur.com/oUJq8BL.png)

**Comment by Indemnity83** [comment]
Addressed in https://github.com/TechnicPack/solder-framework/commit/844f8fc8df186386d64e4cee53e5ab03cc6d8fa7

**Comment by Indemnity83** [comment]
To be clear this is currently part of the `feature/extract-framework` branch and will get rolled into develop when that branch reaches functional parity.

**Comment by Indemnity83** [comment]
Leaving open until the feature branch is merged

**Comment by Pyker** [comment]
This repository is being archived (see <https://www.technicpack.net/article/solderio-is-shutting-down.199> for extra information), so we're closing this issue.
