### ISSUE TITLE
Weird gui behavior in Settings

### ISSUE THREAD

**Issue by bochen415** [SolderIO/solder#134]
When in the settings tab the Key item shows up and vanishes depending on which of the item was clicked.
![](https://i.imgur.com/ForaO9I.gif)

Browser: Chrome 71.0.3578.53 (Official Build) beta (64-bit)

**Comment by Indemnity83** [comment]
"invalid" only because this UI element is being replaced by the work happening in `feature/extract-framework`

Will close formally when the feature branch is merged in.

**Comment by Pyker** [comment]
This repository is being archived (see <https://www.technicpack.net/article/solderio-is-shutting-down.199> for extra information), so we're closing this issue.
