### ISSUE TITLE
[Feature] Attempt to help the user enter the Release version

### ISSUE THREAD

**Issue by bochen415** [SolderIO/solder#136]
When you have all the files set and ready for an update
![](https://i.imgur.com/FDIu8wZ.png)
you need the versions so you can enter those the Version box.
![](https://i.imgur.com/nedT6HF.png)

Solder doesn't help with that.
My idea would be to either:
1. Suggest the version by attempting to get it from the file name and enter it to the Version box for the user to verify, change and save
or
2. Show the complete file name (or the path + file name) so the user could select the part that has the version and copy + paste it in the Version box.

**Comment by Pyker** [comment]
This repository is being archived (see <https://www.technicpack.net/article/solderio-is-shutting-down.199> for extra information), so we're closing this issue.
