### ISSUE TITLE
[Feature] Lose the hyphen, mod authors don't use that

### ISSUE THREAD

**Issue by bochen415** [SolderIO/solder#137]
When generating a slug for a mod, Solder adds an hyphen `-` when it finds spaces and such

![](https://i.imgur.com/sXHxPbu.png)

thing is mod authors don't do that, almost all the mods I'm using just drop the space when the name of the mod is 2 or 3 words.
```
"modid": "lostcities",
 "name": "The Lost Cities"
```
If the mod slug can be considered something that should be similar (or identical) to the modid then the hyphen should be dropped.

My zip file names generated from modids (check the long names):

![](https://i.imgur.com/Zs56oW9.png)

**Comment by Pyker** [comment]
This repository is being archived (see <https://www.technicpack.net/article/solderio-is-shutting-down.199> for extra information), so we're closing this issue.
