### ISSUE TITLE
[Feature] Show when a mod is used by a modpack build or if it's not used at all

### ISSUE THREAD

**Issue by bochen415** [SolderIO/solder#138]
It would be great if solder showed when a specific mod version is used in some build or not used at all.
When you delete a modpack or a modpack build you have plenty of unused mod versions which could be removed safely, 
At this moment there's no way to check that.

![](https://i.imgur.com/cu90M60.png)

**Comment by Pyker** [comment]
This repository is being archived (see <https://www.technicpack.net/article/solderio-is-shutting-down.199> for extra information), so we're closing this issue.
