### ISSUE TITLE
Feel like I am missing something.

### ISSUE THREAD

**Issue by Delinson** [SolderIO/solder#139]
Went through the whole setup process, had no errors at all.

Went to go log into the site, and it shows the directory's (currently how I have it setup).

https://gyazo.com/e16145a5b9538af0766e4988d715184e

So click on public and get this.... 

https://gyazo.com/553da0979a7be5f11792b45c242a320f

More Information:
Fresh Install
Ubuntu 18.10
PHP 7.2.10

**Comment by Pyker** [comment]
The web root is supposed to be the `public` folder.

From the 2nd screenshot, seems like you didn't properly configure your web server to route requests.

**Comment by Delinson** [comment]
I fixed it, turned out it was in my apache config. It did not have the FollowSymLinks option, or the AllowOverride All. Everything is working now, thanks.
