### ISSUE TITLE
Mod Infos not showing on Technicpack

### ISSUE THREAD

**Issue by eliasbnr** [SolderIO/solder#141]
Hey,
Why are the mod info not displayed on the Technicpack page.
![Modpack_1](https://user-images.githubusercontent.com/30735061/55359845-25c4d500-54d3-11e9-94f0-1e2710c45870.jpg)
![Modpack_2](https://user-images.githubusercontent.com/30735061/55359846-25c4d500-54d3-11e9-88e8-aa2123a921c3.jpg)

**Comment by TheGameSpider** [comment]
Technic platform has a cache. You might need to wait a few minutes before the mod's description is updated on your platform site

**Comment by eliasbnr** [comment]
I have been waiting for 1 day and nothing is displayed

**Comment by eliasbnr** [comment]
I added a second mod where also no information is displayed
![Modpack_4](https://user-images.githubusercontent.com/30735061/55431476-efe62600-5590-11e9-87a9-fc0b206ea7ac.jpg)

**Comment by eliasbnr** [comment]
Also if you go to the page "https://solder.domain.tld/api/mod/{mod-slug}?k={api-key}", there is a 404 Error

**Comment by Pyker** [comment]
This repository is being archived (see <https://www.technicpack.net/article/solderio-is-shutting-down.199> for extra information), so we're closing this issue.
