### ISSUE TITLE
Large files can not be uploaded

### ISSUE THREAD

**Issue by eliasbnr** [SolderIO/solder#142]
Hey,
When I try to upload a larger file, an error occurs.
![Modpack_3](https://user-images.githubusercontent.com/30735061/55360205-fb274c00-54d3-11e9-8a20-d98b9f426521.jpg)

**Comment by TheGameSpider** [comment]
Check your post_max_size and upload_max_filesize values in php.ini configuration file

**Comment by eliasbnr** [comment]
Thanks, that worked
