### ISSUE TITLE
Resource Versions should be tagged for their game version

### ISSUE THREAD

**Issue by Indemnity83** [SolderIO/solder#23]
In order to simplify the creation of modpacks; resources should be tagged for the versions of Minecraft they're compatible with. When creating a modpack build, the resource list (and resource versions) can be filtered to only show compatible resources.

**Comment by Pyker** [comment]
This repository is being archived (see <https://www.technicpack.net/article/solderio-is-shutting-down.199> for extra information), so we're closing this issue.
