### ISSUE TITLE
going to /modpacks crashes solder (500)

### ISSUE THREAD

**Issue by zlepper** [SolderIO/solder#33]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Accesing the modpacks page makes solder crash, with a 500

**If the current behavior is a bug, please provide the steps to reproduce**
Access the following url: <https://solder.indemnity83.com/modpacks>

**What is the expected behavior?**
I should see a list of modpacks

**What is the motivation / use case for changing the behavior?**
That people can actually use solder.

**Which versions of Solder, and which browser / http server / PHP versions are affected by this issue? Did this work in previous versions of Solder?**
Solder version: fd7c9d6

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
Error code provided: 6205a9b8-1dc4-4ad4-bc7a-26e9ecdac57f

**Comment by Indemnity83** [comment]
Thanks, 

I had added a column to the builds table in commit 9e1c69e and forgot to update the builds table. I added the column and it works now.
