### ISSUE TITLE
Web File Uploads

### ISSUE THREAD

**Issue by PraveenAlexis** [SolderIO/solder#34]
well wouldn't it be great to have a feature where the modpack creator doesn't have to make specific directory paths, file names etc.. when uploading a mod jar to the solder repository through ftp
instead a file browser through the web browser which the mod jar can be selected and it automatically uploads and creates directories and mod slugs?

i think that would be a great feature
thank you!!
great work

**Comment by Indemnity83** [comment]
Thanks, 

This is generally already planned; but I'm keeping this issue open as the tracking point. Most of what you're talking about exists in the API, it just needs to be implemented in the UI which is in the current phase of the roadmap.

**Comment by Indemnity83** [comment]
Just an update, the API got waylaid (no longer exists in master) so this feature needs to be implemented from scratch whenever ready.

**Comment by Pyker** [comment]
This repository is being archived (see <https://www.technicpack.net/article/solderio-is-shutting-down.199> for extra information), so we're closing this issue.
