### ISSUE TITLE
InvalidArgumentException in UrlGenerator.php line 304: Route [dashboard] not defined.

### ISSUE THREAD

**Issue by 5t0rmr1d3r** [SolderIO/solder#37]
I've checked out the latest version and installed it with your manual.
Everything went fine, until i'll try to login:
Then the site returns the error:
`InvalidArgumentException in UrlGenerator.php line 304: Route [dashboard] not defined.`
how can i solve that?

**Comment by Indemnity83** [comment]
This is something that got injected when I was refactoring a bunch of the code base; I'm working on getting this straightened out (although summer has been a distraction) in parallel with the VUE based front-end. 

I'll leave this open for now, just so others can see the status but basically the application as it stands right now is API only, no GUI component.

**Comment by 5t0rmr1d3r** [comment]
thanks for the reply...

**Comment by Indemnity83** [comment]
This issue no longer applies to the current master branch.
