### ISSUE TITLE
Add form validation and notification to Library

### ISSUE THREAD

**Issue by Indemnity83** [SolderIO/solder#41]
This is a mental dump of the things that need to happen to get the library page (http://solder.indemnity83.com/library) polished up. 

Changes to blade template (.../packages/show.balde.php)
- [ ] Change top notification class from is-primary to is-notification
- [ ] Add `is-danger`to input css for errors on the input
- [ ] Add help text under inputs with errors
- [ ] Add `value="old($field)"` to each input

Anticipated Tests
- [ ] A user can create a modpack
- [ ] A guest cannot create a modpack
- [ ] Name is required
- [ ] Slug is required
- [ ] Slug is unique
- [ ] Slug is alpha numeric

**Comment by Pyker** [comment]
This repository is being archived (see <https://www.technicpack.net/article/solderio-is-shutting-down.199> for extra information), so we're closing this issue.
