### ISSUE TITLE
Add form validation and notification for Release upload form

### ISSUE THREAD

**Issue by Indemnity83** [SolderIO/solder#42]
This is a mental dump of the things that need to happen to get the library page (http://solder.indemnity83.com/library/{package}/) polished up. 

Changes to blade template (.../packages/show.balde.php)
- [ ] Change top notification class from is-primary to is-notification
- [ ] Add `is-danger`to input css for errors on the input
- [ ] Add help text under inputs with errors
- [ ] Add `value="old($field)"` to each input
- [ ] Remove (for now) the hard-coded filename, it's confusing

Anticipated Tests
- [ ] A user can create a release
- [ ] A guest cannot create a release
- [ ] Version is required
- [ ] Version is unique
- [ ] Version contains only numbers, letters, underscore, dash and dots
- [ ] Version cannot start with a dot
- [ ] Archive is a zip file

**Comment by Pyker** [comment]
This repository is being archived (see <https://www.technicpack.net/article/solderio-is-shutting-down.199> for extra information), so we're closing this issue.
