### ISSUE TITLE
Endpoints for solderhelper

### ISSUE THREAD

**Issue by zlepper** [SolderIO/solder#51]
As requested, here is a list of the endpoints solder helpers currently scrappes to do it's thing, and what exactly it uses from them:

* POST /Login
  * Take a wild guess.. (Currently there isn't really a reliable way to check if login has succeeded, so I check if I can find elements from the dashboard)
* POST /modpack/create
  * For creating modpacks, does a normal form post
* POST /mod/create
  * For creating the mods themselves (Creating new versions is seperate)
* POST /mod/add-version
  * For actually adding new mod versions
* POST /mod/rehash
  * Incase a mod version has changed, and solder needs to be told to calculate the new hash
* GET /modpack/build/{buildId}
  * For checking wether a mod is already in a given build (In which case we need to change the active mod version)
  * For checking wether a mod version is active for a build (In which case we don't even need to pack and upload the new version locally)
  * Extending the above: For **actually** getting the mod version active in a build
* POST /modpack/build/modify
  * For adding updating a build, incase the mod is already in a build, but another version is to be used
* GET /mod/view/{modId}
  * For grabbing a mod version id, so it can be used to update the modpack builds
* POST /modpack/add-build/{modpackId}
  * For creating new builds of a modpack
* GET /modpack/view/{modpackId}
  * For getting build ids for updating
  * For figuring out if a new build should be created because it doesn't already exist
* GET /modpack/list
  * For getting the modpack ids themselves
  * For knowing if a new modpack should be created
* GET /mod/list
  * For grabing mod ids
  * For knowing if a mod should be created
* POST /modpack/modify/add
  * For adding a mod version to a build

Everything can be found in details here in terms of parameters and such:<https://github.com/zlepper/go-modpack-packer/blob/angular2/source/backend/solder/solderClient.go>

**Comment by Indemnity83** [comment]
<content removed to reduce confusion>

This info may change rapidly during development; please check the wiki for current documentation

**Comment by Indemnity83** [comment]
I *think* this will be the structure required for all your endpoints. I started documenting endpoints in the wiki so you can check out (and propose changes to) the details of implementation there:

| Scraped Endpoint                    | v0.8 API Endpoint                      |
|-------------------------------------|----------------------------------------|
| POST /mod/rehash                    | Deprecated                             |
| GET /modpack/build/{buildId}        | [GET /api/builds/{build_id}/releases ](../wiki/Package-Releases#browse-all-package-releases-that-belong-to-a-build)   |
| GET /modpack/list                   | [GET /api/modpacks](../wiki/Modpacks#browse-all-modpacks)                      |
| GET /modpack/view/{modpackId}       | [GET /api/modpacks/{modpack_id}/builds](../wiki/Modpacks#browse-all-builds-that-belong-to-a-modpack)  |
| GET /mod/list                       | [GET /api/packages](../wiki/Packages#browse-all-packages)                      |
| GET /mod/view/{modId}               | [GET /api/packages/{package_id}/releases](../wiki/Packages#browse-all-releases-that-belong-to-a-package)                     |
| POST /Login                         |                                    |
| POST /modpack/add-build/{modpackId} | [POST /api/builds](../wiki/Modpack-Builds#add-a-modpack-build)                       |
| POST /modpack/modify/add            | [POST /api/builds/{build_id}/bundles](../wiki/Modpack-Builds#bundle-a-release)                      |
| POST /modpack/build/modify          | [POST /api/builds/{build_id}/bundles/{bundle_id}](../wiki/Bundle#edit-a-bundle)          |
| POST /modpack/create                | [POST /api/modpacks](../wiki/Modpacks#add-a-modpack)                     |
| POST /mod/create                    | [POST /api/packages](../wiki/Packages#add-a-package)                     |
| POST /mod/add-version               | [POST /api/releases](../wiki/Package-Releases#add-a-package-release)                     |
|                                     | [PUT /api/modpacks/{modpack_id}/icon](../wiki/Modpacks#upload-a-modpack-icon)    |
|                                     | [PUT /api/releases/{release_id}/archive](../wiki/Package-Releases#upload-a-file-archive) |

**Comment by Indemnity83** [comment]
Been working on this in the background, the API definition has been pretty well ironed out and can be found here:

https://documenter.getpostman.com/view/465962/solderio/RVnTjfVu

_note that this hasn't been implemented yet, its to be used as a specification going forward_
