### ISSUE TITLE
How to set solder Repo?

### ISSUE THREAD

**Issue by 5t0rmr1d3r** [SolderIO/solder#57]
How can i set the location of the solder repo?
i only found  in the .env file SOLDER_REPO= but that semms to be not working

data is uploaded to 
/var/www/html/solderio/storage/app/public
it seems thats because oft the 
`        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',`
in the /var/www/html/solderio/config/filesystems.php

my repo is located at /var/www/html/repo
the vhost also directs the repo.domain.tld to there (standard solder configuration)

**Comment by 5t0rmr1d3r** [comment]
when i try to upload a new release file it also throws this error
 `ErrorException (E_WARNING)
md5_file(https://solder.domain.tld/storage/chisels-bits/chisels-bits-1.12-14.11.zip): failed to open stream: HTTP request failed! HTTP/1.0 404 Not Found
`
as already mentioned, the file is created here 
/var/www/html/solderio/storage/app/public/chisels-bits/chisels-bits-1.12-14.11.zip

**Comment by Indemnity83** [comment]
Solder v0.8 doesn't quite have the same concept of a "repo" location. It instead uses the Laravel 5.5  File Storage abstraction which makes it so the actual location of files (whether on local disk, or on a service like Amazon S3) is abstracted from the application. 

If you want to change the place where file are stored on your local server you can adjust the root path for the public disk in config/filesystems. More information on that here: https://laravel.com/docs/5.5/filesystem#the-public-disk

That said though, what's the purpose of moving it? Why do you need to have a repo vhost point to the files directly?

As far as your second problem with the MD5 error; have you linked the storage path into the public. Run the following command to create the symbolic link required for the public disk to work:

`php artisan storage:link`

**Comment by 5t0rmr1d3r** [comment]
Thank you for your description.
I'll change my setup in that way, my actual setup was taken from the solder.io wiki.

And for the md5 error I'll execute the artesan command to create the Symlink.

I'll close the issue if everything works as expected tomorrow.
