### ISSUE TITLE
datafield size in database too small

### ISSUE THREAD

**Issue by 5t0rmr1d3r** [SolderIO/solder#58]
i had to increase some datafields (website_url, donation_url and description) of the packages table
![grafik](https://user-images.githubusercontent.com/4589916/34184682-07288748-e519-11e7-8f3e-de9c12c4e76c.png) 
is it possible to increase that by default?

**Comment by Indemnity83** [comment]
Hmm, yeah ... description should have been a text field for sure. is 255 the right number though? thats not much more than the 191 that comes through by default. 

There are some technical trade offs of making the URL's text fields too, but I don't think they have practical implications for the application.

**Comment by 5t0rmr1d3r** [comment]
You're right with the 255 chars, I've taken the next higher number of the largest entry in my database.
As of here link below, 1855 cars should be enough.

https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers



Am December 20, 2017 12:22:34 AM UTC schrieb Kyle Klaus <notifications@github.com>:

**Comment by Indemnity83** [comment]
Wow, thats a heafty field.

**Comment by Indemnity83** [comment]
I ended up making the url's a text field. 

Thanks for reporting!
