### ISSUE TITLE
handling issues with dropdown list of bundle view

### ISSUE THREAD

**Issue by 5t0rmr1d3r** [SolderIO/solder#63]
1. it would be great if the list would be sorted asc with the package name.
![grafik](https://user-images.githubusercontent.com/4589916/35477785-60e57930-03c3-11e8-9eea-a531f818d148.png)

2. could you filter out that list, so that there are only not bundled packages and versions?

**Comment by Indemnity83** [comment]
Yes and Yes; I certainly want both of these things.

**Comment by Indemnity83** [comment]
Sort has been applied; but filtering the list has some precursors. Primarily, the list of bundled packages needs to be converted to VUE, or at least an API endpoint needs to exist so the VUE component that lists available packages knows what is bundled.

**Comment by 5t0rmr1d3r** [comment]
great! thanks a lot!
i would help but i'm not that fit in js, and the structure of the hole project...

**Comment by Pyker** [comment]
This repository is being archived (see <https://www.technicpack.net/article/solderio-is-shutting-down.199> for extra information), so we're closing this issue.
