### ISSUE TITLE
clicking the x in /library links to /settings/general

### ISSUE THREAD

**Issue by Coding-Kiwi** [SolderIO/solder#71]
the x on the top right of "Here is where you store all the mods, resource packs, configs or whatever else you might want to bundle into a modpack. You'll need to create a package to keep multiple versions of the same mod or resource pack together before you can start uploading files."

see title, nothing wild, just wanted to mention it ^^

**Comment by Coding-Kiwi** [comment]
clicking the x on the main page also does that

**Comment by Indemnity83** [comment]
This is actually intentional; just not fully implemented. The x is supposed to take you to the settings to disable the prompts.

**Comment by Indemnity83** [comment]
As an FYI this is controlled currently by the APP_ASSISTANT variable in your .env file

**Comment by Indemnity83** [comment]
PR #87 should address this
