### ISSUE TITLE
The Solder Error

### ISSUE THREAD

**Issue by teddy123434** [SolderIO/solder#72]
I entered my solder, and then he'll show up!
How Can I Do???
![solder error2](https://user-images.githubusercontent.com/20450622/35985239-270ee6f2-0d31-11e8-8359-540521c09f49.png)

**Comment by Indemnity83** [comment]
Looks like you're missing the compiled resources. Run the below command in the root of your solder install to install the node_modules and compile the assets:

```
npm install --only=production
npm run production
```

**Comment by teddy123434** [comment]
I ran the command that you said,but error happened!
This is the errorlog.
1.npm's errorlog
[](https://pastebin.com/BtQdJz0K)
2.running commands errorlog
[](https://pastebin.com/2Z8T0RZu)
Please help me to solve the problem, thank you!
