### ISSUE TITLE
'MD5HashGenerator' Error

### ISSUE THREAD

**Issue by teddy123434** [SolderIO/solder#73]
I ran the command you mentioned in #72 ,but error happened!
This is the errorlog.
1.[npm's errorlog](https://pastebin.com/BtQdJz0K)
2.[running commands errorlog](https://pastebin.com/2Z8T0RZu)
Please help me to solve the problem, thank you!

**Comment by Indemnity83** [comment]
Looks like this might be a known issue with node-sass (sass/node-sass#1579). Try running `npm rebuild node-sass` then running `npm run production`; if that fixes it for you I'll see if I can work the install scripts around the issue.

**Comment by teddy123434** [comment]
Okay,It can login now!
But when I'm adding my mod files,then he'll show up!
![solder error1](https://user-images.githubusercontent.com/20450622/36056717-ba61f4a6-0e41-11e8-98dc-6aa1b14cc22c.png)
Please help me to solve the problem, thank you!

**Comment by Indemnity83** [comment]
I made a new issue for your second problem, see #74 for the fix.
