### ISSUE TITLE
Encryption keys already exist. Use the --force option to overwrite them.

### ISSUE THREAD

**Issue by FinlayDaG33k** [SolderIO/solder#76]
When trying to install solder, I encounter some errors when configuring the MySQL.
When running `php artisan solder:install` I encounter the error `Encryption keys already exist. Use the --force option to overwrite them.` when I have a failed attempt.
The only way to get around it for me is to go back, delete the solder, re-clone it and basically start from scratch.
the `--force` option does not exist.

**Comment by FinlayDaG33k** [comment]
Seems like there is an *undocumented* way to get around this by removing the `.env` file in the `solder` dir.

**Comment by Indemnity83** [comment]
The error you're seeing doesn't actually cause any issues, it can safely be ignored.

**Comment by FinlayDaG33k** [comment]
Any possibility to make it a warning rather than a full-blown error?

**Comment by Indemnity83** [comment]
Yeah, fair point.

**Comment by FinlayDaG33k** [comment]
because it looked like a full-blown error to me, which kinda made me panic about it.
Showing it as a warning (maybe even telling that it *can* be ignored?) should make it more clear that people can ignore it if they want

**Comment by Indemnity83** [comment]
The error is actually coming from a subcommand that I can't change; so I need to either check for the keys before trying to create them, or use the --force option but that will overwrite the keys and invalidate any existing OAuth clients.

**Comment by FinlayDaG33k** [comment]
It doesn't really matter whether it will create new keys or not, but more that the error is represented as a warning (basically telling users: "you can ignore this if you want") rather than an error (basically saying: "something completely went wrong, please fix this first")
