### ISSUE TITLE
Can't install Solder

### ISSUE THREAD

**Issue by FinlayDaG33k** [SolderIO/solder#77]
running `php artisan solder:install` always gives me an error.

The "first" run (after removing the `.env` file and running `php artisan config:clear`) gives me: `SQLSTATE [HY000] [2002] Connection refused`.
Running it a second time (nothing else in between) gives me the error: `Base table or view not found: 1146 Table 'solder.oauth_clients' doesn't exist` (which is extremely obvious since the last attempt resulted in a failed connection).

I have checked my credentials a literal 20 times, and I'm 329523487532490% positive that they are correct.

EDIT: Might it be caused by the fact that the MySQL server is **not** hosted on the local machine (but rather on another machine in the network)

**Comment by Indemnity83** [comment]
I know you said you checked your credentials but the errors are pointing to a problem with your credentials...

You might have a valid username and password, but maybe that user doesn't have the right permissions set on the server? or isn't allowed to connect from the server you're on?

What happens if you just try to connect directly to mysql from your web server 

```
mysql --user=<username> --password <server ip/name>
```

**Comment by FinlayDaG33k** [comment]
It gives the error `Can't connect to local MySQL server through socket`.
Which is odd since the command I'm using is:
`mysql --user=solder --password 10.0.0.148` 

`10.0.0.148` is the server running MySQL (which is as I already said on another machine).

For testing purposes, I have created the following script in PHP:
```

<?php
try{
        $conn = new PDO("mysql:host=10.0.0.148;dbname=solder","solder","SUPERSAUCYPASSWORD");
        if($conn){
                $sql = "CREATE TABLE testtable(ID INT(11) AUTO_INCREMENT PRIMARY KEY)";
                $conn->exec($sql);
        }
} catch (PDOException $e){
        echo $e->getMessage();
}
```

This connects and creates a table without any problem.
The user `solder` has `ALL PRIVILEGES` on DB `solder`

**Comment by FinlayDaG33k** [comment]
Editted the given command a bit: `mysql --user=solder --password -h 10.0.0.148`
it connected just fine then.
then proceeded with creating the test table which also was a success

**Comment by FinlayDaG33k** [comment]
2 hours of testing have passed, and I can only conclude that it's an issue on the side of solder.
All tests here seem to complete properly (connect -> create table -> insert data -> update data -> delete data).

**Comment by Indemnity83** [comment]
Connecting to MySQL though sockets (as you tried when you didn't pass a hostname or if you use the hostname `localhost`) is different than connecting through an IP (as you tried in the later command or if you pass `127.0.0.1`). 

If connecting by ip worked locally, make sure that's the same thing you're specifying in the .env file. You should either have that `10.0.0.148` ip address or you can use `127.0.0.1`.

For more info: https://stackoverflow.com/questions/19712307/mysql-localhost-127-0-0-1

**Comment by FinlayDaG33k** [comment]
Why is this issue being closed?
I have tried it with multiple ways?
By using the local DNS name of the mysql server (`mysql.local`) and the IP of the mysql server (`10.0.0.148`).
Neither of them worked in solder, both of them worked in the MySQL-CLI and the test script I wrote.

As already said:
```
<?php
try{
        $conn = new PDO("mysql:host=10.0.0.148;dbname=solder","solder","test");
        if($conn){
                $sql = "CREATE TABLE testtable(ID INT(11) AUTO_INCREMENT PRIMARY KEY)";
                $conn->exec($sql);
        }
} catch (PDOException $e){
        echo $e->getMessage();
}
```

This little script works.
It is trying to connect to the same host with the same credentials as solder:
```
DB_CONNECTION=mysql
DB_HOST=10.0.0.148
DB_PORT=3306
DB_DATABASE=solder
DB_USERNAME=solder
DB_PASSWORD=test
```

But solder doesn't work, same credentials, same server, both PDO.

Sidenote: yes, for testing purposes, the user password is literally `test`.

**Comment by FinlayDaG33k** [comment]
Also, it would be rather strange that this is an issue with the credentials.
In the first try (delete `.env` and after running `php artisan config:clear`), it says: `connection refused`
![First try](https://i.imgur.com/iAnsdjv.png)

In the second try (same credentials as the first try), it says: `Base table or view not found: 1146 Table 'solder.oauth_clients' doesn't exist`.
![Second try](https://i.imgur.com/YbN7zXh.png)

So in the second try, it connects to the database just fine, but can't find the table needed.

**Comment by Indemnity83** [comment]
Looking at those two back to back; the first time you ran it, it created the .env file. The second time it didn't, but neither time you actually ran the migration?

What happens if you run the install (without deleting the .env) and actually have it run the migration?

**Comment by FinlayDaG33k** [comment]
It seems that it creates everything just fine now.
I have ran `php artisan up`, but now I don't know where to find the app :D
