### ISSUE TITLE
How to access the panel?

### ISSUE THREAD

**Issue by FinlayDaG33k** [SolderIO/solder#81]
So ehm... Finally got the thing installed, but now how do I run and access it?
I have ran `php artisan up` but I can't seem to find how to access it in the browser :\
Not an issue with the code per-se, just something that could be updated in the docs :)

**Comment by Indemnity83** [comment]
Its step 2 of the readme... https://github.com/solderio/solder#step-2

You need to have a webserver.

**Comment by FinlayDaG33k** [comment]
Ah ok, I thought it was some build-in thing :)

**Comment by Indemnity83** [comment]
There is a built in webserver, but its not intended for anything except quick testing. 

```
php artisan serve
```
