### ISSUE TITLE
Able to add the same user multiple times

### ISSUE THREAD

**Issue by FinlayDaG33k** [SolderIO/solder#83]
All the same user...
Think the screenshot tells a lot...
![ehh...](https://i.imgur.com/hYqowIp.png)

**Comment by Noles** [comment]
@Indemnity83 as you like to fully Split Front and Backend. Are you agree to move the 'modpacks/partials/add-collaborators.blade.php' form generation into Vue to allow 'swal' errors and so on for this issue  already?

**Comment by Indemnity83** [comment]
Thats roughly the plan, yes ... here's how I like to structure a page like this

Vue Component Structure

```html
<collaborators inline-template>
     <create-collaborator inline-template>...</create-collaborator>
     <list-collaborators :collaborators="collaborators" inline-template>...</list-collaborators>
</collaborators>
```

So the outermost component is responsible for getting and holding the elements from the API. The list of elements is passed to the list-* component as a prop for display. The list commonly has a delete() method that will broadcast an "updateCollaborators" event upon completion, this will trigger the parent to re-query the server for a new list of collaborators. 

The create-* works in the same basic way, it handles the logic of creating an element, and when thats done it triggers an update event. 

This is more api calls than alternative methods, but it removes all the complications of trying to maintain the correct state of the UI across multiple parent-child components while maintaining the single responsibility principle in the javascript. 

You'll also notice all the components are inline-templates; this lets me develop HTML of the page all at once. I've been doing this on a different project and its much much easier to maintain.

**Comment by Indemnity83** [comment]
There's an example of it in the refactor-platform-api branch here:

https://github.com/solderio/solder/blob/a3441e235e98035d6ef54df996bc2d96812cbbea/resources/views/settings/clients.blade.php#L57-L65

**Comment by Pyker** [comment]
This repository is being archived (see <https://www.technicpack.net/article/solderio-is-shutting-down.199> for extra information), so we're closing this issue.
