### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by 5t0rmr1d3r** [SolderIO/solder#85]
tried to update my install, before now, i didnt had npm.

![grafik](https://user-images.githubusercontent.com/4589916/37257537-ba22b54c-2562-11e8-9792-d99369dbf568.png)

the errorlog:
[npm-debug.log](https://github.com/solderio/solder/files/1800780/npm-debug.log)

**Comment by FinlayDaG33k** [comment]
This means `nodejs` is not installed.
Assuming you have a x86_64 installation of Ubuntu (and not `ARM`, `SystemZ` or `PPC`) follow these instructions:
1. run `wget https://nodejs.org/dist/v9.8.0/node-v9.8.0-linux-x64.tar.xz` (to download the `9.8.0` binaries)
2. run `tar xvf node-v9.8.0-linux-x64.tar.xz` (extract the binaries)
3. run `cd node-v9.8.0-linux-x64` (enter the directory)

Then run the following commands as root to copy everything to the right place:
1. `cp -R bin /usr`
2. `cp -R include /usr`
3. `cp -R lib /usr`
4. `cp -R share /usr`

then rerun `npm install`

**Comment by 5t0rmr1d3r** [comment]
solved, thank you!
