### ISSUE TITLE
Footer text going into the main body

### ISSUE THREAD

**Issue by FinlayDaG33k** [SolderIO/solder#88]
This happens everywhere where the main body exceeds a certain height

![hmm..](https://i.imgur.com/qjdk0Z4.png)

**Comment by 5t0rmr1d3r** [comment]
confirmed in Firefox Quantum

**Comment by FinlayDaG33k** [comment]
Also seems to happen in Edge (version `41.16299.248.0`):
![edgy](https://i.imgur.com/rPaeXzH.png)

**Comment by Indemnity83** [comment]
Thanks guys :)
