### ISSUE TITLE
[Feature] Automatic Changelog Generation

### ISSUE THREAD

**Issue by FinlayDaG33k** [SolderIO/solder#93]
Allow the user to set an optional update message on the build itself rather than having to go to the Technicplatform first

**Comment by Indemnity83** [comment]
Can you expand this a little? What update message are you setting in the platform?

**Comment by FinlayDaG33k** [comment]
Sorry, I ment the changelog :) 
[example](https://www.technicpack.net/modpack/just-a-clusterfuck-of-mods.1057584/changelog)

Right now I have to go to the slow-loading technicplatform and create a changelog there, while it should be do-able from Solder imo.

**Comment by Indemnity83** [comment]
There isn’t any api in technic to accept a change log though

**Comment by FinlayDaG33k** [comment]
hm... bummer...

**Comment by 5t0rmr1d3r** [comment]
But it would be also awsome to have an autocreated changelog to copy + paste

**Comment by FinlayDaG33k** [comment]
That indeed would be a major step forward.

**Comment by Indemnity83** [comment]
How would you propose the changelog be generated?

**Comment by FinlayDaG33k** [comment]
not really ideal, but it's a start:
If the build is copied, then check it against the previous version (where it is cloned from)

**Comment by Pyker** [comment]
This repository is being archived (see <https://www.technicpack.net/article/solderio-is-shutting-down.199> for extra information), so we're closing this issue.
